conferenceroom/urls.py
from django.urls import path
from.import views

app_name = 'conferenceroom'
urlpatterns= [
#URLS for myapp1 app
     #dashboard
     path('index',views.IndexView.as_view(), name="my_index_view"),
     path('accomodation',views.AccomodationView.as_view(), name="my_accomodation_view"),     
     path('registration',views.RegistrationView.as_view(), name="my_registration_view"),
     path('signin',views.SignInView.as_view(), name="my_signin_view"),          
     path('about',views.AboutUsView.as_view(), name="my_aboutus_view"),
     path('contact',views.ContactView.as_view(), name="my_contact_view"),
     path('room',views.RoomView.as_view(), name="my_room_view"),
     path('addroom',views.AddRoomView.as_view(), name="my_addroom_view"),
     #urls after signing in
     path('roomdashboard',views.RoomDashboardView.as_view(), name="my_roomdashboard_view"),
     path('aboutwuser',views.AboutUsViewWUser.as_view(), name="my_aboutuswuser_view"),
     path('accomodationwuser',views.AccomodationViewWUser.as_view(), name="my_accomodationwuser_view"),
     path('indexwuser',views.IndexViewWUser.as_view(), name="my_indexwuser_view"),
     path('contactwuser',views.ContactViewWUser.as_view(), name="my_contactwuser_view"),
     #######admin#######
     path('admin',views.AdminView.as_view(), name="my_admin_view"),
     path('adminabout',views.AdminAboutView.as_view(), name="my_admin_about_view"),
     path('admincontact',views.AdminContactView.as_view(), name="my_admin_contact_view"),
     path('adminindex',views.AdminIndexView.as_view(), name="my_admin_index_view"),
     path('admindashboard',views.AdminDashboardView.as_view(), name="my_admin_dashboard_view"),
     ]

nameless/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf import settings
from django.conf.urls.static import static

app_name = 'conferenceroom'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('conferenceroom/', include('conferenceroom.urls',namespace='conferenceroom')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

conferenceroom/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.db import connections

# Create your models here.
#USER DETAILS DATABASE
class User(models.Model):
    username = models.CharField(max_length=100,unique =True,blank = False)
    password = models.CharField(max_length=100,blank = False)
    emailadd = models.CharField(max_length=100, unique = True,blank = False)
    fname = models.CharField(max_length=50,blank = False)
    lname = models.CharField(max_length=50,blank = False)
    address = models.CharField(max_length=50,blank = False)
    contactNum = models.CharField(max_length=50, default = False,blank = False)
#USER ROOM DETAILS DATABASE
class Room(models.Model):
    slot = models.CharField(max_length=50,blank = False, unique=False)
    roomtype = models.CharField(max_length=50)
    dateofuse = models.DateField(max_length=50,blank=True, null=True,default='')
    username = models.ForeignKey(User,to_field='username', related_name='username+', on_delete=models.CASCADE)
    class meta:
        db_table = 'nameless_room'
class RoomReservation(models.Model):
    roomnumber = models.CharField(max_length=50, unique = True)
    roomtype = models.CharField(max_length=50)
    dateofuse = models.CharField(max_length=50)
    timeuse = models.CharField(max_length=50)
    username = models.CharField(max_length=50)
    emailadd = models.CharField(max_length=50)
    contactNum = models.CharField(max_length=50)
    address = models.CharField(max_length=100)
    class meta:
        db_table = 'nameless_roomreservation'
#ADMIN ADD ROOM DETAILS DATABASE
class AddRoom(models.Model):
    roomnumber = models.CharField(max_length=50, unique = True)
    roomtype = models.CharField(max_length=50)
    class meta:
        db_table = 'nameless_addroom'

conferenceroom/forms.py
from django import forms
from .models import *

class RoomForm(forms.ModelForm):
	class Meta:
		model = Room
		fields= '__all__'
class RoomReservationForm(forms.ModelForm):
	class Meta:
		model = RoomReservation
		fields= '__all__'
class AddRoomForm(forms.ModelForm):
	class Meta:
		model = AddRoom
		fields= '__all__'
class UserForm(forms.ModelForm):
	class Meta:
		model = User
		fields= '__all__'

conferenceroom/views.py
from django.shortcuts import render
from django.http import Http404
from django.shortcuts import render, redirect
from django.views.generic import View
from django.http import HttpResponse
from .forms import *
from .models import *
from django.db.models import Count
from django.db.models import Max
# Create your views here.
class IndexView(View):
	def get(self, request):
		return render(request,'index.html',{})
class AccomodationView(View): 
	def get(self, request):
		return render(request,'accomodation.html',{})
class SignInView(View): 
	def get(self, request):
		return render(request, 'signin.html',{})
	def post(self, request):

		if request.method == 'POST':
			username= request.POST.get("username")
			password = request.POST.get("password")
			check_user = User.objects.filter(username=username,password=password)

			if check_user:
				request.session['usern'] = username
				if User.objects.filter(username=username).count()>0:
					return redirect('/conferenceroom/indexwuser')
				elif User.objects.filter(username='admin').count()>0:
					return redirect('/conferenceroom/admin')
				else:
					return redirect('/conferenceroom/signin.html')
		else:	
			return render(request,"signup.html", context)
class RegistrationView(View): 
	def get(self, request):
		user = User.objects.all()
		context = {
			'user':user,
		}
		return render(request,'registration.html',context)
	def post(self, request):		
		form = UserForm(request.POST)		
		if form.is_valid():
			username = request.POST.get("username")
			password = request.POST.get("password")
			emailadd = request.POST.get("emailadd")
			fname = request.POST.get("fname")
			lname = request.POST.get("lname")
			address = request.POST.get("address")
			contactNum = request.POST.get("contactNum")

			form = User(username=username,password=password,emailadd=emailadd,fname=fname,lname=lname,address=address,contactNum=contactNum)
			form.save()	
			return redirect('/conferenceroom/signin')
		else:
			print(form.errors)
			return HttpResponse('not valid')
class AboutUsView(View):
	def get(self, request):
		return render(request, 'about.html',{})
		
class ContactView(View):
	def get(self, request):
		return render(request, 'contact.html',{})
class RoomView(View):
	def get(self, request):
		if 'usern' in request.session:
			current_user = request.session['usern']
			addroom = AddRoom.objects.all()
			userdetails = User.objects.filter(username=current_user)
			context = {
				'userdetails':userdetails,
				'addroom':addroom,
		}
		return render(request,'room.html',context)
	def post(self, request):		
		form = RoomForm(request.POST)		
		if form.is_valid():
			slot = request.POST.get("slot")
			roomtype = request.POST.get("roomtype")
			dateofuse = request.POST.get("dateofuse")
			username = request.POST.get("username")
			form = Room(slot=slot,roomtype = roomtype, dateofuse = dateofuse, username_id=username)
			form.save()	
			return redirect('/conferenceroom/roomdashboard')
		else:
			print(form.errors)
			return HttpResponse('not valid')
class RoomDashboardView(View):
	def get(self, request):
		if 'usern' in request.session:
			current_user = request.session['usern']
			room = Room.objects.filter(username=current_user)
			#count_date = Room.objects.values('dateofuse').order_by('dateofuse').annotate(count=Count('dateofuse'))
			userdetails = User.objects.filter(username=current_user)
			context = {
				'userdetails':userdetails,
				'room':room,
			#	'count_date':count_date,
		}
		return render(request,'roomdashboard.html',context)
	def post(self, request):
			if 'BtnUpdate_user'in request.POST:
				username = request.POST.get("username") 
				password = request.POST.get("password")
				emailadd = request.POST.get("emailadd")
				fname = request.POST.get("fname")
				lname = request.POST.get("lname")
				address = request.POST.get("address")
				contactNum = request.POST.get("contactNum")
				print(username)		
				update_user = User.objects.filter(username = username).update(password=password,emailadd=emailadd,fname=fname,lname=lname,address=address,contactNum=contactNum)
				print(update_user)
				print('User Updated')
				return redirect('/conferenceroom/roomdashboard')
			elif 'BtnDelete_user' in request.POST:
				iddn = request.POST.get("id") 
				iddn= User.objects.filter(id = iddn).delete()
				print('deleted')
				return redirect('/conferenceroom/roomdashboard')
			elif 'BtnUpdate_room'in request.POST:
				username = request.POST.get("username") 
				slot = request.POST.get("slot") 
				dateofuse = request.POST.get("dateofuse")
				roomtype = request.POST.get("roomtype")	
				update_room = Room.objects.filter(username = username).update(slot=slot,dateofuse=dateofuse,roomtype=roomtype)
				print('Room Updated')
				return redirect('/conferenceroom/roomdashboard')
			elif 'BtnDelete_room' in request.POST:
				iddn = request.POST.get("id") 
				iddn= Room.objects.filter(id = iddn).delete()
				print('deleted')
				return redirect('/conferenceroom/roomdashboard')
			
class AddRoomView(View):
	def get(self, request):
		return render(request, 'addroom.html',{})
	def post(self, request):
		form = AddRoomForm(request.POST)
		if form.is_valid():
			roomnumber = request.POST.get("roomnumber")
			roomtype = request.POST.get("roomtype")
			form = AddRoom(roomnumber=roomnumber,roomtype = roomtype)
			form.save()	
			return redirect('/conferenceroom/roomdashboard')
		else:
			print(form.errors)
			return HttpResponse('not valid')


######################views with user######################################################################################
class AboutUsViewWUser(View):
	def get(self, request):
		if 'usern' in request.session:
			current_user = request.session['usern']
			userdetails = User.objects.filter(username=current_user)
			context = {
			'userdetails':userdetails,
			}
class AdminDashboardView(View):
	def get(self, request):
		if 'usern' in request.session:
			current_user = request.session['usern']
			userdetails = User.objects.filter(username=current_user)
			count_date = Room.objects.values('dateofuse').order_by('dateofuse').annotate(count=Count('dateofuse'))
			#room = Room.objects.values('roomtype').annotate(count=Count('roomtype'))
			#room_max = room.aggregate(Max('roomtype')
			context = {
			'userdetails':userdetails,
			'count_date':count_date
			}
		return render(request,'admindashboard.html', context)
class AccomodationViewWUser(View):
	def get(self, request):
		if 'usern' in request.session:
			current_user = request.session['usern']
			userdetails = User.objects.filter(username=current_user)
			#room = Room.objects.values('roomtype').annotate(count=Count('roomtype'))
			#room_max = room.aggregate(Max('roomtype')
			context = {
			'userdetails':userdetails,
			}
		return render(request,'accomodationwuser.html', context)
class IndexViewWUser(View):
	def get(self, request):
		if 'usern' in request.session:
			current_user = request.session['usern']
			userdetails = User.objects.filter(username=current_user)
			context = {
			'userdetails':userdetails,
			}
		return render(request,'indexwuser.html', context)
class ContactViewWUser(View):
	def get(self, request):
		if 'usern' in request.session:
			current_user = request.session['usern']
			userdetails = User.objects.filter(username=current_user)
			context = {
			'userdetails':userdetails,
			}
		return render(request,'contactwuser.html', context)
	
####################################admin views ####################
class AdminView(View):
	def get(self, request):
		if 'usern' in request.session:
			current_user = request.session['usern']
			userdetails = User.objects.filter(username=current_user)
			room = Room.objects.values('roomtype').annotate(count=Count('roomtype')).latest('count')
			#order_by().annotate(count=Count('roomtype'))
			#room = Room.objects.aggregate(max=Max('roomtype'))
			count_date = Room.objects.values('dateofuse').annotate(count=Count('dateofuse'))
			context = {
			'userdetails':userdetails,
			'room':room,
			'count_date':count_date
			}
		return render(request,'admin.html', context)
class AdminAboutView(View):
	def get(self, request):
		if 'usern' in request.session:
			current_user = request.session['usern']
			userdetails = User.objects.filter(username=current_user)
			#room = Room.objects.values('roomtype').order_by().annotate(count=Count('roomtype'))
			#room = Room.objects.aggregate(max=Max('roomtype'))
			room = Room.objects.values('roomtype').annotate(count=Count('roomtype'))
			count_date = Room.objects.values('dateofuse').annotate(count=Count('dateofuse'))
			context = {
			'userdetails':userdetails,
			'room':room,
			'count_date':count_date,
			}
		return render(request,'adminabout.html', context)
class AdminContactView(View):
	def get(self, request):
		if 'usern' in request.session:
			current_user = request.session['usern']
			userdetails = User.objects.filter(username=current_user)
			room = Room.objects.values('roomtype').order_by().annotate(count=Count('roomtype'))
			#room = Room.objects.aggregate(max=Max('roomtype'))
			count_date = Room.objects.values('dateofuse').annotate(count=Count('dateofuse'))
			context = {
			'userdetails':userdetails,
			'room':room,
			'count_date':count_date
			}
		return render(request,'admincontact.html', context)
class AdminIndexView(View):
	def get(self, request):
		if 'usern' in request.session:
			current_user = request.session['usern']
			userdetails = User.objects.filter(username=current_user)
			room = Room.objects.values('roomtype').order_by().annotate(count=Count('roomtype'))
			#room = Room.objects.aggregate(max=Max('roomtype'))
			count_date = Room.objects.values('dateofuse').annotate(count=Count('dateofuse'))
			context = {
			'userdetails':userdetails,
			'room':room,
			'count_date':count_date
			}
		return render(request,'adminindex.html', context)

conferenceroom/templates/adminindex.html
<!doctype html>
<html lang="en">
    {% load static %}

    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="icon" href="{% static 'media/favicon2.png' %}">
        <title>Sedon Dantes</title>
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'vendors/linericon/style.css' %}">
        <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'vendors/bootstrap-datepicker/bootstrap-datetimepicker.min.css' %}">
        <link rel="stylesheet" href="{% static 'vendors/nice-select/css/nice-select.css' %}">
        <link rel="stylesheet" href="{% static 'vendors/owl-carousel/owl.carousel.min.css' %}">
        <!-- main css -->
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
    </head>
    <body>
        <!--================Header Area =================-->
        <header class="header_area">
            <div class="container">
                <nav class="navbar navbar-expand-lg navbar-light">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <a class="navbar-brand logo_h" href="{% url 'conferenceroom:my_index_view' %}"><img src="{% static 'media/sedonlogo.png' %}" alt=""></a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse offset" id="navbarSupportedContent">
                        <ul class="nav navbar-nav menu_nav ml-auto">
                            <li class="nav-item active"><a class="nav-link" href="{% url 'conferenceroom:my_admin_index_view' %}">Home</a></li> 
                            <li class="nav-item"><a class="nav-link" href="{% url 'conferenceroom:my_admin_about_view' %}">About us</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'conferenceroom:my_admin_view' %}">Services</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'conferenceroom:my_admin_contact_view' %}">Contact Us</a></li>
                      <!--      <li class="nav-item"><a class="nav-link" href="elements.html">Elemests</a></li>-->
                      {% for userdetails in userdetails %}
                      <li class="nav-item"><a class="nav-link" href="{% url 'conferenceroom:my_admin_dashboard_view' %}">{{userdetails.username}}</a></li>
                      {% endfor %} 
                            <li class="nav-item submenu dropdown">
                                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Menu</a>
                                <ul class="dropdown-menu">
                                    <li class="nav-item"><a class="nav-link" href="{% url 'conferenceroom:my_admin_about_view' %}">About us</a></li>
                                    <li class="nav-item"><a class="nav-link" href="{% url 'conferenceroom:my_admin_view' %}">Services</a></li>
                                    <li class="nav-item"><a class="nav-link" href="{% url 'conferenceroom:my_admin_contact_view' %}">Contact Us</a></li>
                                    {% for userdetails in userdetails %}
                                    <li class="nav-item"><a class="nav-link" href="{% url 'conferenceroom:my_signin_view' %}">{{userdetails.username}}</a></li>
                                    {% endfor %} 
                                </ul>
                    </div> 
                </nav>
            </div>
        </header>
        <!--================Header Area =================-->
        
        <!--================Banner Area =================-->
        <section class="banner_area">
            <div class="booking_table d_flex align-items-center">
                <div class="overlay bg-parallax" data-stellar-ratio="0.9" data-stellar-vertical-offset="0" data-background=""></div>
                <div class="container">
                    <div class="banner_content text-center">
                        <h6>Conduct Elaborate Meetings</h6>
                        <h2>Sedon Dantes</h2>
                        <p>If you are looking for a complete and good quality conference room, you are in the right place.</p>
                        <a href="https://www.facebook.com/candog5" target="_blank" class="genric-btn success radius button_hover">Get Started</a>
                    </div>
                </div>
            </div>
            
        </section>
        <!--================Banner Area =================-->
        
        <!--================ Accomodation Area  =================-->
        
        <!--================ Accomodation Area  =================-->
        
        <!--================ Facilities Area  =================-->
        
        <!--================ Facilities Area  =================-->
        
        <!--================ About History Area  =================-->
        
        <!--================ About History Area  =================-->
        
        <!--================ Testimonial Area  =================-->
        
        <!--================ Testimonial Area  =================-->
        
        <!--================ Latest Blog Area  =================-->
        
        <!--================ Recent Area  =================-->
        
        <!--================ start footer Area  =================-->    
<footer class="footer-area section_gap">
            <div class="container">
                <div class="row">
                    <div class="col-lg-3  col-md-6 col-sm-6">
                        <div class="single-footer-widget">
                            <h6 class="footer_title">About Agency</h6>
                            <p>The world has become so fast paced that people don’t want to stand by reading a page of information, they would much rather look at a presentation and understand the message. It has come to a point </p>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6 col-sm-6">
                        <div class="single-footer-widget">
                            <h6 class="footer_title">Navigation Links</h6>
                            <div class="row">
                                <div class="col-4">
                                    <ul class="list_style">
                                        <li><a href="#">Home</a></li>
                                        <li><a href="#">Feature</a></li>
                                        <li><a href="#">Services</a></li>
                                        <li><a href="#">Portfolio</a></li>
                                    </ul>
                                </div>
                                <div class="col-4">
                                    <ul class="list_style">
                                        <li><a href="#">Team</a></li>
                                        <li><a href="#">Pricing</a></li>
                                        <li><a href="#">Blog</a></li>
                                        <li><a href="#">Contact</a></li>
                                    </ul>
                                </div>                                      
                            </div>                          
                        </div>
                    </div>                          
                    <div class="col-lg-3 col-md-6 col-sm-6">
                        <div class="single-footer-widget">
                            <h6 class="footer_title">Newsletter</h6>
                            <p>For business professionals caught between high OEM price and mediocre print and graphic output, </p>     
                            <div id="mc_embed_signup">
                                <form target="_blank" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01" method="get" class="subscribe_form relative">
                                    <div class="input-group d-flex flex-row">
                                        <input name="EMAIL" placeholder="Email Address" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Email Address '" required="" type="email">
                                        <button class="btn sub-btn"><span class="lnr lnr-location"></span></button>     
                                    </div>                                  
                                    <div class="mt-10 info"></div>
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6 col-sm-6">
                        <div class="single-footer-widget instafeed">
                            <h6 class="footer_title">InstaFeed</h6>
                            <ul class="list_style instafeed d-flex flex-wrap">
                                <li><img src="{% static 'media/instagram/Image-01.jpg' %}" alt=""></li>
                                <li><img src="{% static 'media/instagram/Image-02.jpg' %}" alt=""></li>
                                <li><img src="{% static 'media/instagram/Image-03.jpg' %}" alt=""></li>
                                <li><img src="{% static 'media/instagram/Image-04.jpg' %}" alt=""></li>
                                <li><img src="{% static 'media/instagram/Image-05.jpg' %}" alt=""></li>
                                <li><img src="{% static 'media/instagram/Image-06.jpg' %}" alt=""></li>
                                <li><img src="{% static 'media/instagram/Image-07.jpg' %}" alt=""></li>
                                <li><img src="{% static 'media/instagram/Image-08.jpg' %}" alt=""></li>
                            </ul>
                        </div>
                    </div>                      
                </div>
                <div class="border_line"></div>
                <div class="row footer-bottom d-flex justify-content-between align-items-center">
                    <p class="col-lg-8 col-sm-12 footer-text m-0"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
                    <div class="col-lg-4 col-sm-12 footer-social">
                        <a href="#"><i class="fa fa-facebook"></i></a>
                        <a href="#"><i class="fa fa-twitter"></i></a>
                        <a href="#"><i class="fa fa-dribbble"></i></a>
                        <a href="#"><i class="fa fa-behance"></i></a>
                    </div>
                </div>
            </div>
        </footer>
        <!--================ End footer Area  =================-->
        
        
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
        <script src="{% static 'js/popper.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'vendors/owl-carousel/owl.carousel.min.js' %}"></script>
        <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
        <script src="{% static 'vendors/bootstrap-datepicker/bootstrap-datetimepicker.min.js' %}"></script>
        <script src="{% static 'vendors/nice-select/js/jquery.nice-select.js' %}"></script>
        <script src="{% static 'js/mail-script.js' %}"></script>
        <script src="{% static 'js/stellar.js' %}"></script>
        <script src="{% static 'vendors/lightbox/simpleLightbox.min.js' %}"></script>
        <script src="{% static 'js/custom.js' %}"></script>
    </body>
</html>